import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useEffect, useState, } from 'react'
import axios from 'axios';
import { getAllChannels } from "@/database";

function wait(seconds) {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve()
        }, seconds * 1000)
    })
}


export default function Channels({channels}) {

    const [create, setCreate] = useState (false)

//   const [channels, setChannels] = useState([])

//   useEffect(() => {
//     axios.get("/api/channels")
//     .then((response) => {
//       setChannels(response.data)
//     })
//   })
  return (
    <div className={styles.container}>
        <Head>
            <title>Discord Clone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div  className={styles.main}>
            <h1 className={styles.title} >Channels</h1>
            <button className={styles.formButton} type="submit" onClick={() => setCreate(!create)}>Create New Channel</button>
                {create ? 
                    <form className={styles.form}>
                    <label> Channel name:</label><input className={styles.formUsername} placeholder="Insert channel name" type="text"  /> 
                    <button className={styles.formButton} type="submit">Create</button>
                    </form>
                : null}

                    <ul className={styles.channelsContainer}>
                        {channels.map((channels) => (
                            <li key={channels.id} className={styles.channels}> {channels.id} - {channels.name}</li>
                            ))}
                    </ul>
        </div>
    </div>
)
}

export async function getServerSideProps() {

// runs on the server
const channels = await getAllChannels();

return {
    props: {
        channels: JSON.parse(JSON.stringify(channels))
    }
}

}