import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import { useEffect, useState, } from 'react'

// import axios from 'axios';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/notdiscord.svg" /> */}
      </Head>

      <main className={styles.main}>
        <Image src="/notdiscord.svg" width={100} height={100} alt="knock off version of the discord logo"/>
        <h1 className={styles.title}>Welcome to NOT Discord </h1> <br/>
        <div className={styles.card}>
          <Link href="/channels"><h2> View Channels</h2></Link>
        </div>
       
      </main>
    </div>
  )
}
